apiVersion: v1
kind: Service
metadata:
  name: frvsrganv
  labels:
    app: frvsrgan-train
spec:
  selector:
    app: frvsrgan-train
  ports:
    - protocol: TCP
      port: 8097
      targetPort: frvsrganv-port
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: visdom
  annotations:
    # using kubernetes/ingress-nginx controller
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /

    # SSL
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: "true"

    # websocket
    nginx.ingress.kubernetes.io/proxy-send-timeout: "86400"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"

spec:
  tls:
    - hosts:
        - frvsrgan1.c.videogorillas.com
      secretName: tls-secret

  rules:
    - host: frvsrgan1.c.videogorillas.com
      http:
        paths:
          - backend:
              serviceName: frvsrganv
              servicePort: frvsrganv-port

---
apiVersion: batch/v1
kind: Job
metadata:
  name: train-frvsrgan
spec:
  backoffLimit: 0
  parallelism: 1
  template:
    metadata:
      labels:
        app: frvsrgan-train
    spec:
      imagePullSecrets:
        - name: regcred42
      restartPolicy: Never
      containers:
        - image: k10:31337/up4k:frvsrgan1
          imagePullPolicy: Always
          name: frvsrgan
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
            - mountPath: /svlk
              name: svlk-volume
            - mountPath: /storage
              name: storage-volume
          env:
            # 0=Quadro P6000
            # 1=GeForce GTX TITAN
            - name: NVIDIA_VISIBLE_DEVICES
              value: "0"
          command:
            - python
            - "FRVSRGAN_Train.py"
            - "-o"
            - "/svlk/zhuker_train/frvsrgan1"
            - "-b"
            - "2"
            - "--visdom_host"
            - "http://frvsrganv"
            - "--resume_dir"
            - "epochs"
          resources:
            limits:
              nvidia.com/gpu: 1
        - image: k10:31337/up4k:frvsrgan1
          imagePullPolicy: IfNotPresent
          name: frvsrganv
          command:
            - "visdom"
          ports:
            - containerPort: 8097
              hostPort: 8097
              name: frvsrganv-port


      nodeSelector:
        #        feature.node.kubernetes.io/gfd-nvidia-memory: "24449"
        #        feature.node.kubernetes.io/gfd-nvidia-memory: "8117"

        #        feature.node.kubernetes.io/gfd-nvidia-model: Tesla-K80
        feature.node.kubernetes.io/gfd-nvidia-model: GeForce-GTX-1070
        feature.node.videogorillas.com/storage-speed: "10" #10gbe or direct access
        #        feature.node.kubernetes.io/gfd-nvidia-model: Quadro-P6000


      volumes:
        - name: dshm
          emptyDir:
            medium: Memory

        - name: svlk-volume
          hostPath:
            # directory location on host
            path: /svlk
            # this field is optional
            type: Directory

        - name: storage-volume
          hostPath:
            # directory location on host
            path: /storage
            # this field is optional
            type: Directory
